name: Review pull request

"on":
  pull_request_target:
    types: [assigned]

jobs:
  review:
    runs-on: review
    if: >-
      contains(github.event.pull_request.assignees.*.login, 'clive') &&
      !contains(github.event.pull_request.labels.*.name, 'under-review')
    concurrency:
      group: review-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    uses: https://forgejo.hel.bm.internal/bannermedia/review-bot/.forgejo/workflows/review.yml@main
    secrets:
      REVIEW_BOT_TOKEN: ${{ secrets.REVIEW_BOT_TOKEN }}
